version: '3'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
    - 8080:80
    volumes:
    - C:\Users\rebel\Projects\portfolio_wp_theme:/var/www/html/wp-content/themes/portfolio
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: mysql123
      WORDPRESS_DB_NAME: wp
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql123